relativePath = fullfile('..', '..', 'data', 'ingasn单点tof图像测试.mat');
load(relativePath);
c=rect_data(3,3,:);
cc=reshape(c,1,191);
T_min = min(cc(:));
T_max = max(cc(:));
T_normalized = (cc - T_min) / (T_max - T_min);
figure;
 set(gcf,'Position',[100 100 400 300]);
n=length(T_normalized);
x_new = 5 * (1:n);
plot(x_new, T_normalized,'LineWidth', 1.5);
set(gca, 'FontName', 'Times New Roman','FontWeight','bold', 'FontSize', 14);
xlabel('Arrival Time(ps)', 'FontSize', 16, 'FontName', 'Times New Roman');
ylabel('Normalized Photon Counts', 'FontSize', 16, 'FontName', 'Times New Roman');
% xlim([310 560]);
ylim([0 1.1]);
ax = gca;
currentPosition = get(ax, 'Position'); 
newPosition = [0.19 0.19 0.74 0.74];
set(ax, 'Position', newPosition);